# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kUEIpsUe0ulRFEcixEiEAxlp05CdaZEz
"""

#scientific calculator
import math
import time
def show_list():
  print("\n---scientific calculator---")
  print("1.addition")
  print("2.substraction")
  print("3.multiplication")
  print("4.division")
  print("5.power")
  print("6.square root")
  print("7.factorial")
  print("8.sine")
  print("9.cosine")
  print("10.tangent")
  print("11.logarithm(base10)")
  print("12.natural log (ln)")
  print("13.exponential(e^x)")
  print("14.exit")

def main():
  while True:
    show_list()
    choice=int(input("enter an operation(1-14)"))

    if choice == 14:
      print(" exiting the calculator")
      break

    if choice in [1,2,3,4,5]:
      a=float(input("enter the first number"))
      b=float(input("enter the second number"))

      if choice == 1:
        print("result:",a+b)

      if choice == 2:
        print("result:",a-b)

      if choice == 3:
        print("result:",a*b)

      if choice == 4:
        if b != 0:
          print("result:",a/b)
        else:
          print("can't divide by zero")

    elif choice == 5:
      a=float(input("enter the first number"))
      b=float(input("enter the second number"))
      print("result:", math.pow(a,b))

    elif choice == 6:
      x=float(input("enter a number"))
      print("result:",math.sqrt(x))

    elif choice == 7:
      x=int(input("enter a number (integer only)"))
      print("result:",math.factorial(x))

    elif choice in [8,9,10]:
      angle = float(input("enter an angle in degrees"))
      radians = math.radians(angle)

      if choice == 8:
        print("result:",math.sin(radians))

      elif choice == 9:
        print("result:",math.cos(radians))

      elif choice == 10:
        print("result:",math.tan(radians))

    elif choice == 11:
      x=float(input("enter a number"))
      print("logarithm base 10:",math.log10(x))

    elif choice == 12:
      x=float(input("enter a number"))
      print("natural log (ln):",math.log(x))

    elif choice == 13:
      x=float(input("enter a number"))
      print("exponential (e^x):",math.exp(x))

    else:
      print("invalid choice, please try again")

      time.sleep(1)

main()